name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_EXECUTOR: LocalExecutor
        envkey_REPO: apache/airflow
        file_name: .env

    - uses: actions/checkout@v2
    
    - name: Create airflow env
      run: make up
    
    - name: Execute dags
      run: make test
    
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    
    - name: Run validation tests
      run: python tests/test.py
